"""spaced reviews

Revision ID: 20260831_0006
Revises: 20260824_0005
Create Date: 2026-08-31 14:22:42.670931
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "20260831_0006"
down_revision: str | Sequence[str] | None = "20260824_0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review_preferences",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("study_days", sa.JSON(), nullable=False),
        sa.Column("reminder_time", sa.String(length=5), nullable=False),
        sa.Column("reminder_enabled", sa.Boolean(), nullable=False),
        sa.Column("schedule_mode", sa.String(length=16), nullable=False),
        sa.Column("fixed_interval_days", sa.Integer(), nullable=False),
        sa.Column("desired_retention", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "review_reminders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("due_count", sa.Integer(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dismissed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "local_date", name="uq_review_reminder_daily"),
    )
    op.create_index(
        op.f("ix_review_reminders_user_id"), "review_reminders", ["user_id"], unique=False
    )
    op.create_table(
        "review_cards",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("error_cluster_id", sa.String(length=36), nullable=False),
        sa.Column("fsrs_state", sa.JSON(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("algorithm_due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["error_cluster_id"],
            ["error_clusters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("error_cluster_id"),
    )
    op.create_index("ix_review_cards_user_due", "review_cards", ["user_id", "due_at"], unique=False)
    op.create_index(op.f("ix_review_cards_user_id"), "review_cards", ["user_id"], unique=False)
    op.create_table(
        "review_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("card_id", sa.String(length=36), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("card_revision", sa.Integer(), nullable=False),
        sa.Column("response", sa.Text(), nullable=False),
        sa.Column("exercise", sa.JSON(), nullable=False),
        sa.Column("feedback", sa.Text(), nullable=False),
        sa.Column("rule_matched", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["review_cards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("card_id", "card_revision", name="uq_review_attempt_revision"),
        sa.UniqueConstraint("user_id", "request_id", name="uq_review_attempt_request"),
    )
    op.create_index(
        op.f("ix_review_attempts_card_id"), "review_attempts", ["card_id"], unique=False
    )
    op.create_index(
        op.f("ix_review_attempts_user_id"), "review_attempts", ["user_id"], unique=False
    )
    op.create_table(
        "review_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("card_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_id", sa.String(length=36), nullable=False),
        sa.Column("rating", sa.String(length=16), nullable=False),
        sa.Column("before_state", sa.JSON(), nullable=False),
        sa.Column("after_state", sa.JSON(), nullable=False),
        sa.Column("scheduler_config", sa.JSON(), nullable=False),
        sa.Column("fsrs_log", sa.JSON(), nullable=False),
        sa.Column("algorithm_due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["review_attempts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["review_cards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attempt_id"),
    )
    op.create_index(op.f("ix_review_logs_card_id"), "review_logs", ["card_id"], unique=False)
    op.create_index(op.f("ix_review_logs_user_id"), "review_logs", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_review_logs_user_id"), table_name="review_logs")
    op.drop_index(op.f("ix_review_logs_card_id"), table_name="review_logs")
    op.drop_table("review_logs")
    op.drop_index(op.f("ix_review_attempts_user_id"), table_name="review_attempts")
    op.drop_index(op.f("ix_review_attempts_card_id"), table_name="review_attempts")
    op.drop_table("review_attempts")
    op.drop_index(op.f("ix_review_cards_user_id"), table_name="review_cards")
    op.drop_index("ix_review_cards_user_due", table_name="review_cards")
    op.drop_table("review_cards")
    op.drop_index(op.f("ix_review_reminders_user_id"), table_name="review_reminders")
    op.drop_table("review_reminders")
    op.drop_table("review_preferences")
    # ### end Alembic commands ###
